pyscripter/python4delphi

PythonForDelphi/Components/Sources/Core/PythonEngine.pas
Hi,
Please review and merge these changes:
1. SetPythonHome - required for instance for supporting OSGEO4W Python without setting environment variable externally. (setting environment variable internally from within the app doesn't work for PythonHome, thus the use of this function)
2. Ansi/UTF8 eval/execute according to Python version
3. silent a redundant warning
RE: Option to use latest DLL: needed for machines with both 2.7 and 3.x that want to use 3.x. changes the version search to be reversed (last version is tested first)
You wrote: Have a look at PythonVersions.pas. It does all that and more. 
Please advise how to make Python4delphi prefer the newer python version.
Kind Regards,
Idan
=> SetPythonHome; Ansi/UTF8 eval; warning sielnt

Demos/Demo07/test.py
This concerns test.py under Demo07
=> Made Python 3 compatible

Demos/Demo23/Unit1.dfm, Demos/Demo23/threading_test.py
This should fix issue #198, at least for demo 23.
See also the comments there.
=> Updates for demo 23

Source/WrapDelphi.pas, Source/WrapFireDAC.pas, Tests/WrapDelphiTest.pas
... and also support for calling class method
=> rtti method invoke with dynamic array as parameter

Demos/FMX/BasicTypes/PointF/MainForm.fmx, Demos/FMX/BasicTypes/PointF/MainForm.pas, Demos/FMX/BasicTypes/PointF/PointF.dpr, Demos/FMX/BasicTypes/PointF/PointF.dproj, Source/WrapDelphi.pas, Source/fmx/WrapFmxControls.pas, Source/fmx/WrapFmxTypes.pas
**TPointF wrapper**
* The TPointF type is primarily used for the coordinates of FireMonkey objects.
**FMX.Types.TFmxObject wrapper**
* Parent property access.
**FMX.Controls.TControl wrapper**
* Show and Hide (VCL) methods are represented by Visible property (FMX);
* ClientToScreen (VCL) is relative to LocalToAbsolute (FMX);
* ScreenToClient (VCL) is relative to AbsoluteToLocal (FMX);
* Invalidate and Update (VCL) are not available (FMX);
* Child controls access;
* Focus routines access.
=> Wrappers - FMX Base Types

Source/WrapDelphi.pas, Tests/WrapDelphiTest.pas
hi, PR has 2 improvements:
1. returned dynamic array to python list conversion
2. more flexible searching in FindMethod - when a few methods has the same name and param count then method with unsupported var should be skiped  and find should try another with different parameters type
=> array return & better overload

Source/fmx/WrapFmxControls.pas, Source/fmx/WrapFmxTypes.pas
**FMX.Types.TPosition wrapper**
* A TPosition object is used for representing the position of a control inside its parent, or anywhere related X and Y values are needed.
**FMX.Controls.TControl wrapper**
* Position property access.
=> Giving access to the position property of a control

Source/fmx/WrapFmxControls.pas, Source/fmx/WrapFmxTypes.pas
**FMX.Types.TPosition wrapper**
* TSizeF represents the floating-point size of an object using the Width and Height properties (will be allocated in WrapSysTypes)
**FMX.Controls.TStyledControl wrapper**
* DefaultStyleLookupName property access;
* StyleLookup property access;
* AutoTranslate property access;
* AdjustSizeValue property access;
* AdjustType property access;
* StyleState property access;
* ApplyStyleLookup method access;
* NeedStyleLookup method access;
* Inflate method access.
=> Styledcontrolwrapper

Source/fmx/WrapFmxControls.pas
**FMX.Controls.TTextControl wrapper**
* Specifies the text that will be rendered over the surface of this TTextControl object.
**FMX.Controls.TStyleBook wrapper**
* TStyleBook stores a collection of styles for a form.
**FMX.Controls.TPopup wrapper**
* TPopup provides a pop-up window.
=> Fmxcontrolswrappers

Source/fmx/WrapFmxDialogs.pas
**FMX.Dialogs wrappers**
* TOpenDialog wrapper
=> Fmx Dialogs wrappers

Source/fmx/WrapFmxComCtrls.pas, Source/fmx/WrapFmxDialogs.pas, Source/fmx/WrapFmxShapes.pas
**FMX.Objects wrappers**
* TShape;
* TLine;
* TRectangle;
* TCaretRectangle;
* TRoungRect;
* TCalloutRectangle;
* TEllipse;
* TCircle;
* TPie;
* TArc;
* TCustomPath;
* TPath;
* TText;
* TImage;
* TPaintBox;
* TSelection;
* TSelectionPoint.
=> Fmx shapes wrappers

Source/fmx/WrapFmxComCtrls.pas, Source/fmx/WrapFmxDialogs.pas, Source/fmx/WrapFmxForms.pas, Source/fmx/WrapFmxGrids.pas, Source/fmx/WrapFmxLayouts.pas, Source/fmx/WrapFmxScrollBox.pas, Source/fmx/WrapFmxShapes.pas
**FMX.Grid wrappers**
* TColumn;
* TStringColumn;
* TProgressColumn;
* TCheckColumn;
* TDateTimeColumnBase;
* TDateTimeColumn;
* TTimeColumn;
* TDateColumn;
* TPopupColumn;
* TImageColumn;
* TCustomNumberColumn;
* TCurrencyColumn;
* TFloatColumn;
* TIntegerColumn;
* TGlyphColumn;
* TCustomGrid;
* TGrid;
* TStringGrid.
=> Fmx grids wrappers

Source/PythonEngine.pas
I need to be dependencies automatically satisfied for user scripts, but pip module requires this method in stdout.
Fixed by two lines:)
=> isatty method in DebugOutput class for better compability

Demos/FMX/FormDemo/FormDemo.dpr, Demos/FMX/FormDemo/FormDemo.dproj, Demos/FMX/FormDemo/MainForm.fmx, Demos/FMX/FormDemo/MainForm.pas, Demos/FMX/FormDemo/SecondForm.fmx, Demos/FMX/FormDemo/SecondForm.pas, Source/fmx/WrapDelphiFmx.pas, Source/fmx/WrapFmxForms.pas
**FMX form demo project**
* Simple FMX form demo project
=> Fmx form demo

Source/WrapDelphi.pas, Tests/WrapDelphiTest.pas
hi - this is another fix for a situation if I try to call via rtti a method like this
pas: 
`  procedure PassVariantArray(const Value: Variant);`
with list as parameter
py: 
`  rtti_var.PassVariantArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`
but I got an exception - "Invalid variant type conversion" in SimplePythonToValue->TValue.FromVariant. This method(FromVariant) is ok for simple types but array should stay "as is" in Variant.
=> rtti invoke - variant parameter with array inside

Source/WrapDelphi.pas, Source/WrapFireDAC.pas
=> const is faster

Source/PythonEngine.pas
=> const is faster part 2

Packages/Delphi/Delphi 10.4+/PythonFmx.dpk, Source/fmx/WrapDelphiFmx.pas, Source/fmx/WrapFmxEdit.pas, Source/fmx/WrapFmxListBox.pas
Adding missing types:
- TEdit
- TListBox
=> Missingtypes

Modules/DelphiFMX/DelphiFMX.dpr, Modules/DelphiFMX/DelphiFMX.dproj, Modules/DelphiFMX/TestFMX.py, Modules/DelphiFMX/uMain.pas, Packages/Delphi/Delphi 10.4+/PythonFmx.dpk, Source/fmx/WrapDelphiFmx.pas, Source/fmx/WrapFmxEdit.pas, Source/fmx/WrapFmxListBox.pas
=> Fmxsamples

Source/PythonEngine.pas
It's a fix for a problem I found doing threading controlled outside p4d. With optimizations enabled, delphi treats PyGILState_STATE enum as 1-byte by default, but vc++ compiled python.dll has it as a 4-byte enum. Calls to PyGILState_Release with a 1-byte argument (decompiled to something like mov al, 0; call PyGILState_Release;) leads to unexpected behaviour because most significant bytes could have "random" values, depending on what happens to the AX register before calling.
For this fix, I have only internal tests for my system,  but I think it can be important for someone else
=> PyGILState_Release correction

.gitignore, Source/WrapDelphi.pas, Tests/P4DTests.dpr, Tests/WrapDelphiEventHandlerTest.pas
... function  CreateVarParam(PyDelphiWrapper : TPyDelphiWrapper; AObject: TObject) : PPyObject; overload;
=> WrapDelphi.CreateVarParam with object - a small helpful overload
